CREATE TABLE Employees (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(50),
    PhoneNo VARCHAR(12),
    DeptId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Departments(Id) ON UPDATE CASCADE ON DELETE SET NULL
)